<?php
/**
 * YellowPages feedback forms module.
 */

/**
 * Implements hook_block_info().
 */
function yellow_pages_feedback_block_info() {
  $blocks = array();

  $blocks['yp_ad_request'] = array(
    'info' => 'YellowPages Advertisement Request',
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function yellow_pages_feedback_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'yp_ad_request':
      $form = drupal_get_form('yellow_pages_feedback_ad_request');
      $block['subject'] = t('Advertisement request');
      $block['content'] = drupal_render($form);
      break;
  }

  return $block;
}

/**
 * Implements hook_mail().
 */
function yellow_pages_feedback_mail($key, &$message, $params) {
  switch ($key) {
    case 'yp_feedback_ad':
      $body_t = array(
        '@name' => $params['name'],
        '@company' => $params['company'],
        '@phone' => $params['telephone'],
        '@email' => $params['email'],
        '@adv_type' => $params['adv_type'],
      );
      $message['to'] = $params['to'];
      $message['subject'] = t('Advertisement request');
      $message['body'][] = t('@name from @company wants to post an advertisement!', $body_t);
      $message['body'][] = t('Contact phone: @phone', $body_t);
      $message['body'][] = t('Contact email: @email', $body_t);
      $message['body'][] = t('Advertisement type: @adv_type', $body_t);
      break;
  }
}

/**
 * Implements hook_theme().
 */
function yellow_pages_feedback_theme($existing, $type, $theme, $path) {
  $hooks = array();

  return $hooks;
}

function yellow_pages_feedback_ad_request($form, &$form_state) {
  $form['company_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Company name'),
    '#required' => TRUE,
    '#default_value' => '',
  );

  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email'),
    '#required' => FALSE,
    '#default_value' => '',
  );

  $form['telephone'] = array(
    '#type' => 'textfield',
    '#title' => t('Telephone'),
    '#required' => TRUE,
    '#default_value' => '',
  );

  $form['contact_person'] = array(
    '#type' => 'textfield',
    '#title' => t('Contact person'),
    '#required' => TRUE,
    '#default_value' => '',
  );

  $form['adv_type'] = array(
    '#type' => 'textarea',
    '#title' => t('What type of advertising are you interested in?'),
    '#default_value' => '',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

function yellow_pages_feedback_ad_request_submit($form, &$form_state) {
  $values = $form_state['values'];
  $role = user_role_load_by_name('global editor');

  $query = 'SELECT DISTINCT(ur.uid)
  FROM {users_roles} AS ur
  WHERE ur.rid IN (:rids)';
  $result = db_query($query, array(':rids' => $role->rid));

  $uids = $result->fetchCol();

  $users = user_load_multiple($uids);

  $to = '';
  foreach ($users as $user) {
    $to .= ', ' . $user->mail;
  }

  $params = array(
    'name' => $values['contact_person'],
    'company' => $values['company_name'],
    'telephone' => $values['telephone'],
    'email' => $values['email'],
    'adv_type' => $values['adv_type'],
    'to' => $to,
  );
  $dm = drupal_mail('yellow_pages_feedback', 'yp_feedback_ad', $to, language_default(), $params, NULL, TRUE);

  if ($dm['result']) {
    drupal_set_message(t('Thank you, we will contact you soon.'));
  }
}

function yellow_pages_feedback_ad_request_validate($form, &$form_state) {
  $values = $form_state['values'];

  if (!valid_email_address($values['email'])) {
    form_set_error('email', t('The email address is not valid.'));
  }
}

include_once 'yellow_pages_feedback.features.inc';
