; This file was auto-generated by drush make
core = 7.x
api = 2

; Contrib modules
projects[addressfield][version] = "1.1"
projects[addressfield][subdir] = "contrib"

projects[admin_views][version] = "1.5"
projects[admin_views][subdir] = "contrib"

projects[ckeditor][version] = "1.16"
projects[ckeditor][subdir] = "contrib"

projects[coder][version] = "2.5"
projects[coder][subdir] = "contrib"

projects[colorbox][version] = "2.10"
projects[colorbox][subdir] = "contrib"

projects[ctools][version] = "1.9"
projects[ctools][subdir] = "contrib"

projects[date][version] = "2.9"
projects[date][subdir] = "contrib"

projects[devel][version] = "1.5"
projects[devel][subdir] = "contrib"

projects[email][version] = "1.3"
projects[email][subdir] = "contrib"

projects[entity][version] = "1.6"
projects[entity][subdir] = "contrib"

projects[entityreference][version] = "1.1"
projects[entityreference][subdir] = "contrib"

projects[facetapi][version] = "1.5"
projects[facetapi][subdir] = "contrib"
projects[facetapi][patch][] = "https://www.drupal.org/files/issues/2311585-3-facetapi-7.x-2.x-translate_more_link.patch"
projects[facetapi][patch][] = "http://am.storage.dev.inlead.dk/facetapi_accents-sort.patch"

projects[field_sql_norevisions][version] = "2.1"
projects[field_sql_norevisions][subdir] = "contrib"

projects[features][version] = "2.6"
projects[features][subdir] = "contrib"

projects[features_extra][version] = "1.0"
projects[features_extra][subdir] = "contrib"

projects[file_entity][version] = "2.0-beta2"
projects[file_entity][subdir] = "contrib"

projects[field_group][version] = "1.4"
projects[field_group][subdir] = "contrib"

projects[field_permissions][version] = "1.0-beta2"
projects[field_permissions][subdir] = "contrib"

projects[fontawesome][version] = "2.1"
projects[fontawesome][subdir] = "contrib"

projects[forward][version] = "2.0"
projects[forward][subdir] = "contrib"

projects[geocoder][version] = "1.2"
projects[geocoder][subdir] = "contrib"

projects[geofield][version] = "2.3"
projects[geofield][subdir] = "contrib"

projects[geophp][version] = "1.7"
projects[geophp][subdir] = "contrib"

projects[i18n][version] = "1.13"
projects[i18n][subdir] = "contrib"

projects[l10n_update][version] = "2.0"
projects[l10n_update][subdir] = "contrib"

projects[libraries][version] = "2.2"
projects[libraries][subdir] = "contrib"

projects[jquery_update][version] = "2.6"
projects[jquery_update][subdir] = "contrib"

projects[leaflet][version] = "1.2"
projects[leaflet][subdir] = "contrib"

projects[libraries][version] = "2.2"
projects[libraries][subdir] = "contrib"

projects[link][version] = "1.3"
projects[link][subdir] = "contrib"

projects[mailsystem][version] = "2.34"
projects[mailsystem][subdir] = "contrib"

projects[media][type] = "module"
projects[media][subdir] = "contrib"
projects[media][download][type] = "git"
projects[media][download][url] = "http://git.drupal.org/project/media.git"
projects[media][download][revision] = "199e5013dc9915a3d67d73d681a1db6ba56b63e6"

projects[media_colorbox][version] = "1.0-rc4"
projects[media_colorbox][subdir] = "contrib"

projects[media_youtube][version] = "3.0"
projects[media_youtube][subdir] = "contrib"

projects[mimemail][version] = "1.0-beta4"
projects[mimemail][subdir] = "contrib"

projects[module_filter][version] = "2.0"
projects[module_filter][subdir] = "contrib"

projects[navigation404][version] = "1.0"
projects[navigation404][subdir] = "contrib"

projects[node_expire][version] = "1.8"
projects[node_expire][subdir] = "contrib"

projects[opening_hours][version] = "1.5"
projects[opening_hours][subdir] = "contrib"

projects[owlcarousel][version] = "1.5"
projects[owlcarousel][subdir] = "contrib"
projects[owlcarousel][patch][] = "http://am.storage.dev.inlead.dk/owlcarousel-fixed_libraries_owlcarousel_path.patch"

projects[panels][version] = "3.5"
projects[panels][subdir] = "contrib"

projects[rules][version] = "2.9"
projects[rules][subdir] = "contrib"

projects[search_api][version] = "1.16"
projects[search_api][subdir] = "contrib"

projects[search_api_solr][version] = "1.9"
projects[search_api_solr][subdir] = "contrib"

projects[service_links][version] = "2.3"
projects[service_links][subdir] = "contrib"

projects[socialfield][version] = "1.4"
projects[socialfield][subdir] = "contrib"

projects[strongarm][version] = "2.0"
projects[strongarm][subdir] = "contrib"

projects[taxonomy_menu][version] = "1.5"
projects[taxonomy_menu][subdir] = "contrib"

projects[tipsy][version] = "1.0-rc1"
projects[tipsy][subdir] = "contrib"

projects[token][version] = "1.6"
projects[token][subdir] = "contrib"

projects[transliteration][version] = "3.2"
projects[transliteration][subdir] = "contrib"

projects[variable][version] = "2.5"
projects[variable][subdir] = "contrib"

projects[views][version] = "3.11"
projects[views][subdir] = "contrib"

projects[views_autocomplete_filters][version] = "1.2"
projects[views_autocomplete_filters][subdir] = "contrib"

projects[views_bulk_operations][version] = "3.3"
projects[views_bulk_operations][subdir] = "contrib"

projects[nodeviewcount][version] = "2.3"
projects[nodeviewcount][subdir] = "contrib"

projects[bootstrap][version] = "3.0"

; Libraries
libraries[fontawesome][destination]    = "libraries"
libraries[fontawesome][directory_name] = "fontawesome"
libraries[fontawesome][download][type] = "get"
libraries[fontawesome][download][url]  = "http://fortawesome.github.io/Font-Awesome/assets/font-awesome-4.4.0.zip"

libraries[leaflet][destination]    = "libraries"
libraries[leaflet][directory_name] = "leaflet"
libraries[leaflet][download][type] = "get"
libraries[leaflet][download][url]  = "http://cdn.leafletjs.com/downloads/leaflet-0.7.3.zip"

libraries[owl-carousel][destination]    = "libraries"
libraries[owl-carousel][directory_name] = "owl-carousel"
libraries[owl-carousel][download][type] = "get"
libraries[owl-carousel][download][url]  = "http://owlgraphic.com/owlcarousel/owl.carousel.zip"
