<?php
/**
 * @file
 * Code for the Yellow pages company CT feature.
 */

 define('YP_PRODUCT_SELL', 1);
 define('YP_PRODUCT_BUY', 2);
 define('YP_PRODUCT_MANUFACTURE', 4);
 define('YP_PRODUCT_SERVICES', 8);

include_once 'yellow_pages_company_ct.features.inc';
require_once 'yellow_pages_company_ct.fields.inc';

/**
 * Implements hook_menu().
 */
function yellow_pages_company_ct_menu() {
  $menu = array();

  $menu['yp/autocomplete/product'] = array(
    'title' => 'Autocomplete for products',
    'page callback' => '_products_autocomplete',
    'access arguments' => array('use autocomplete'),
    'type' => MENU_CALLBACK,
  );

  return $menu;
}

/**
 * Provides product terms suggestons.
 *
 * @param string $input
 *   String to search related terms on.
 */
function _products_autocomplete($input) {
  $query = db_select('taxonomy_term_data', 't')
    ->fields('t', array('tid', 'name'));
  $query->join('field_data_field_product_type', 'fpt', 't.tid = fpt.entity_id');
  $query->condition('fpt.field_product_type_value', YP_TERM_TYPE_PRODUCT, '=');
  $query->condition('t.name', '%' . db_like($input) . '%', 'LIKE');
  $result = $query->execute()->fetchAll();

  $response = array();

  foreach ($result as $r) {
    $response[$r->name . ' [tid:' . $r->tid . ']'] = $r->name;
  }

  echo drupal_json_output($response);
  drupal_exit(0);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function yellow_pages_company_ct_form_company_node_form_alter(&$form, &$form_state, $form_id) {
  // Make sync date field readonly.
  $form['field_mdb_sync_date']['#disabled'] = TRUE;
}

/**
 * Implements hook_entity_view().
 */
function yellow_pages_company_ct_entity_view($entity, $entity_type, $view_mode, $langcode) {
  $is_company_page = $entity->type == 'company' && $entity_type == 'node' && $view_mode == 'full';

  if (!$is_company_page) {
    return;
  }

  $source_map = array(
    YP_PRODUCT_BUY => 'group_we_buy',
    YP_PRODUCT_SELL => 'group_we_sell',
    YP_PRODUCT_MANUFACTURE => 'group_products',
    YP_PRODUCT_SERVICES => 'group_services',
  );

  if (!empty($entity->field_company_products)) {
    foreach ($entity->field_company_products[LANGUAGE_NONE] as $k => $item) {
      $term = $item['taxonomy_term'];
      $target_group = $source_map[$item['product_source']];
      $target_group_field = $target_group . '_content';

      $entity->content[$target_group_field][$k] = array(
        '#type' => 'link',
        '#title' => $term->name,
        '#href' => url('search/companies', array('absolute' => TRUE)) . '?f[0]=field_company_products%253Aproduct%253Aparents_all%3A' . $term->tid,
        '#group' => $target_group,
      );

      $entity->content['#fieldgroups'][$target_group]->children = array(
        $target_group_field,
      );
    }
  }
}
