<?php
/**
 * @file
 * Core functionality, not suitable to be specifically placed anywhere else.
 */

include_once 'yellow_pages_core.fields.inc';

/**
 * Implements hook_menu().
 */
function yellow_pages_core_menu() {
  $items = array();

  $items['admin/config/yp'] = array(
    'title' => 'Yellow Pages',
    'description' => 'Yellow Pages related settings',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  // @todo
  // CSRF token
  $items['node/%node/geomap'] = array(
    'title' => 'Geo map',
    'description' => 'Rendered map for certain node',
    'page callback' => 'yellow_pages_core_node_geomap',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['node/%node/print'] = array(
    'title callback' => 'node_page_title',
    'title arguments' => array(1),
    'page callback' => 'yellow_pages_core_node_print',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Print node page callback.
 */
function yellow_pages_core_node_print($node) {
  drupal_set_title($node->title);
  $nodes = node_view_multiple(array($node->nid => $node), 'print_mode');

  return $nodes;
}

/**
 * Implements hook_entity_info_alter().
 */
function yellow_pages_core_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['print_mode'] = array(
    'label' => t('Print mode'),
    'custom settings' => TRUE,
  );
}

/**
 * Return field renderable array with a map for a certain node.
 *
 * @param stdClass $node
 *   The node object.
 *
 * @return array
 *   Render array with geo field data.
 */
function yellow_pages_core_node_geomap(stdClass $node) {
  $entity = $node;
  $entity_type = 'node';
  $geo_items = field_get_items($entity_type, $entity, 'field_geocode');

  if (!$geo_items) {
    return drupal_not_found();
  }

  $settings = array(
    'geofield_map_baselayers_hybrid' => 1,
    'geofield_map_baselayers_map' => 1,
    'geofield_map_baselayers_physical' => 0,
    'geofield_map_baselayers_satellite' => 1,
    'geofield_map_center' => array(
      'geocode' => 'Find my location',
      'lat' => '',
      'lon' => ''
    ),
    'geofield_map_controltype' => 'default',
    'geofield_map_draggable' => 1,
    'geofield_map_height' => '768px',
    'geofield_map_maptype' => 'map',
    'geofield_map_max_zoom' => 0,
    'geofield_map_min_zoom' => 0,
    'geofield_map_mtc' => 'none',
    'geofield_map_overview' => 0,
    'geofield_map_overview_opened' => 0,
    'geofield_map_pancontrol' => 1,
    'geofield_map_scale' => 1,
    'geofield_map_scrollwheel' => 1,
    'geofield_map_streetview_show' => 1,
    'geofield_map_width' => '100%',
    'geofield_map_zoom' => 18,
  );

  $field = array('field_name' => 'field_address');
  $instance = array();
  $langcode = LANGUAGE_NONE;

  $geo_map = geofield_map_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $geo_items, array('settings' => $settings));

  $geo_map['#prefix'] = "<h1>{$entity->title}</h1>";

  drupal_set_title($entity->title . variable_set('site_name', 'YELLOW PAGES OF MOLDOVA'));

  return $geo_map;
}

/**
 * Implements hook_FORM_ID_alter().
 *
 * Enrich site settings with additional description field.
 */
function yellow_pages_core_form_system_site_information_settings_alter(&$form, &$form_state) {
  $form['site_information']['site_description'] = array(
    '#type' => 'textfield',
    '#title' => t('Site description'),
    '#default_value' => variable_get('site_description'),
  );

  $form['site_information']['site_mail']['#weight'] = '99';
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds a password reset link.
 */
function yellow_pages_core_form_user_login_alter(&$form, &$form_state) {
  $form['pass_reset'] = array(
    '#type' => 'item',
    '#markup' => l(t('Request new password'), 'user/password', array('attributes' => array('title' => t('Request new password via e-mail.')))),
  );
}

/**
 * Implements hook_user_logout().
 */
function yellow_pages_core_user_logout($account) {
  // Unset cookies.
  if (isset($_SERVER['HTTP_COOKIE'])) {
    $cookies = explode(';', $_SERVER['HTTP_COOKIE']);
    foreach($cookies as $cookie) {
      $parts = explode('=', $cookie);
      $name = trim($parts[0]);
      setrawcookie($name, '', REQUEST_TIME - 3600, '/');
    }
  }
}

/**
 * Callback function that finds node translations.
 * @param int $tnid
 *   Translation node id.
 *
 * @return array
 *   Array of translation node nids with language as array-keys.
 */
function yellow_pages_core_node_get_translation_nids($tnid) {
  $translations = array();
  $result = db_select('node', 'n')
    ->fields('n', array('nid', 'language'))
    ->condition('n.tnid', $tnid)
    ->execute();

  foreach ($result as $node) {
    $langcode = $node->language;
    $translations[$langcode] = $node->nid;
  }

  return $translations;
}

/**
 * Creating date collection between two dates
 *
 * @param string $first
 *   Timestamp since.
 * @param string $last
 *   Timestamp until.
 * @param string $step
 * @param string $output_format
 *   Format of output dates.
 *
 * @return array of dates.
 */
function yellow_pages_core_date_range($first, $last, $step = '+1 day', $output_format = 'd/m/Y', $key_format = 'Ymd') {
  $dates = array();
  $current = $first;

  while( $current <= $last ) {
    $key = date($key_format, $current);
    $dates[$key] = format_date($current, 'custom', $output_format);
    $current = strtotime($step, $current);
  }

  return $dates;
}

/**
 * Get weekdays' names for current language.
 *
 * @return array
 *   Array of all weekdays translated full names.
 */
function yellow_pages_core_get_weekdays() {
  return array(
    'Monday' => t('Monday'),
    'Tuesday' => t('Tuesday'),
    'Wednesday' => t('Wednesday'),
    'Thursday' => t('Thursday'),
    'Friday' => t('Friday'),
    'Saturday' => t('Saturday'),
    'Sunday' => t('Sunday')
  );
}

/**
 * Get day hours from 00:00 to 24:00 with half hour range.
 *
 * @return array
 *   Array of times strings.
 */
function yellow_pages_core_get_day_hours() {
  $day_hours = array();
  for ($i = 0; $i <= 96; $i++) {
    $j = $i * 15;
    $h = (int) ($j / 60);
    $m = $j % 60;
    $hour = str_pad($h, 2, '0', STR_PAD_LEFT) . ":" . str_pad($m, 2, '0', STR_PAD_RIGHT);
    $day_hours[$hour] = $hour;
  }

  return $day_hours;
}

/**
 * Implements hook_media_browser_plugins_alter().
 */
function yellow_pages_core_media_browser_plugins_alter(&$plugin_output) {
  $path = drupal_get_path('module', 'yellow_pages_core');
  drupal_add_css($path . '/css/yellow_pages_core_media_browser.css');
  if (!empty($plugin_output['upload']['form']['#options']['file_extensions'])) {
    $ext = trim($plugin_output['upload']['form']['#options']['file_extensions']);
    $ext_array = explode(' ', $ext);
    foreach ($ext_array as &$extension) {
      $extension = '.' . $extension;
    }
    $ext_list = implode(', ', $ext_array);
    $plugin_output['upload']['form']['upload']['upload']['#attributes']['accept'] = $ext_list;
  }
}

/**
 * Implements hook_block_info()
 */
function yellow_pages_core_block_info() {
  $blocks['adsense_300_250'] = array(
    'info' => t('AdSense 300x250'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['adsense_front_468_60_left'] = array(
    'info' => t('AdSense 468x60 left'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['adsense_news_728_90'] = array(
    'info' => t('AdSense News'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );


  $blocks['adsense_front_468_60_right'] = array(
    'info' => t('AdSense 468x60 right'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['adsense_front_980_120'] = array(
    'info' => t('AdSense 980x120'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function yellow_pages_core_block_view($delta = '') {
  $block = array(
    'subject' => '',
  );

  switch ($delta) {
    case 'adsense_300_250':
      $block['content'] = yellow_pages_core_get_adsense_300_250();
      break;

    case 'adsense_front_468_60_right':
    case 'adsense_front_468_60_left':
      $block['content'] = yellow_pages_core_get_adsense_468_60();
      break;

    case 'adsense_news_728_90':
      $block['content'] = yellow_pages_core_get_adsense_728_90();
      break;

    case 'adsense_front_980_120':
      $block['content'] = yellow_pages_core_get_adsense_980_120();

      break;
  }

  return $block;
}

/**
 * Get AdSense ad for 728x90px block.
 */
function yellow_pages_core_get_adsense_728_90() {
  if (in_array($_SERVER['SERVER_NAME'], array('yp.md', 'www.yp.md'))) {
    return '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- adoptive_www.yp.md -->
<ins class="adsbygoogle"
style="display:block"
data-ad-client="ca-pub-4252189351312901"
data-ad-slot="2224086432"
data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>';
  } else {
    return '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- adoptive-www.yellowpages.md -->
<ins class="adsbygoogle"
style="display:block"
data-ad-client="ca-pub-4252189351312901"
data-ad-slot="1891902181"
data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>';
  }
}


/**
 * Get google AdSense block for 300x250.
 */
function yellow_pages_core_get_adsense_300_250() {
   if (in_array($_SERVER['SERVER_NAME'], array('yp.md', 'www.yp.md'))) {
  return '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- 300x250px_yp.md -->
<ins class="adsbygoogle"
style="display:inline-block;width:300px;height:250px"
data-ad-client="ca-pub-4252189351312901"
data-ad-slot="7543305270"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>';
  } else {
    return '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- yellowpages.md_300x250px -->
<ins class="adsbygoogle"
style="display:inline-block;width:300px;height:250px"
data-ad-client="ca-pub-4252189351312901"
data-ad-slot="1584816871"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>';
  }
}


/**
 * Get google AdSense 468x60.
 */
function yellow_pages_core_get_adsense_468_60() {
  if (in_array($_SERVER['SERVER_NAME'], array('yp.md', 'www.yp.md'))) {
    return '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- adoptive_www.yp.md -->
<ins class="adsbygoogle"
style="display:block"
data-ad-client="ca-pub-4252189351312901"
data-ad-slot="2224086432"
data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>';
  }
  else {
    return '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- adoptive-www.yellowpages.md -->
<ins class="adsbygoogle"
style="display:block"
data-ad-client="ca-pub-4252189351312901"
data-ad-slot="1891902181"
data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>';
  }
}

/**
 * Get google AdSense block for 980x120.
 */
function yellow_pages_core_get_adsense_980_120() {
  return '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- yp.md&yellowpages.md_980x120px -->
<ins class="adsbygoogle"
style="display:inline-block;width:980px;height:120px"
data-ad-client="ca-pub-4252189351312901"
data-ad-slot="2403474871"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>';
}
