<?php
/**
 * @file
 * Core functionality, not suitable to be specifically placed anywhere else.
 */

include_once 'yellow_pages_core.fields.inc';

/**
 * Implements hook_menu().
 */
function yellow_pages_core_menu() {
  $items = array();

  $items['admin/config/yp'] = array(
    'title' => 'Yellow Pages',
    'description' => 'Yellow Pages related settings',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  return $items;
}

/**
 * Implements hook_FORM_ID_alter().
 *
 * Enrich site settings with additional description field.
 */
function yellow_pages_core_form_system_site_information_settings_alter(&$form, &$form_state) {
  $form['site_information']['site_description'] = array(
    '#type' => 'textfield',
    '#title' => t('Site description'),
    '#default_value' => variable_get('site_description'),
  );

  $form['site_information']['site_mail']['#weight'] = '99';
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds a password reset link.
 */
function yellow_pages_core_form_user_login_alter(&$form, &$form_state) {
  $form['pass_reset'] = array(
    '#type' => 'item',
    '#markup' => l(t('Request new password'), 'user/password', array('attributes' => array('title' => t('Request new password via e-mail.')))),
  );
}

/**
 * Implements hook_user_logout().
 */
function yellow_pages_core_user_logout($account) {
  // Unset cookies.
  if (isset($_SERVER['HTTP_COOKIE'])) {
    $cookies = explode(';', $_SERVER['HTTP_COOKIE']);
    foreach($cookies as $cookie) {
      $parts = explode('=', $cookie);
      $name = trim($parts[0]);
      setrawcookie($name, '', REQUEST_TIME - 3600, '/');
    }
  }
}

/**
 * Callback function that finds node translations.
 * @param int $tnid
 *   Translation node id.
 *
 * @return array
 *   Array of translation node nids with language as array-keys.
 */
function yellow_pages_core_node_get_translation_nids($tnid) {
  $translations = array();
  $result = db_select('node', 'n')
    ->fields('n', array('nid', 'language'))
    ->condition('n.tnid', $tnid)
    ->execute();

  foreach ($result as $node) {
    $langcode = $node->language;
    $translations[$langcode] = $node->nid;
  }

  return $translations;
}

/**
 * Creating date collection between two dates
 *
 * @param string $first
 *   Timestamp since.
 * @param string $last
 *   Timestamp until.
 * @param string $step
 * @param string $output_format
 *   Format of output dates.
 *
 * @return array of dates.
 */
function yellow_pages_core_date_range($first, $last, $step = '+1 day', $output_format = 'd/m/Y', $key_format = 'Ymd') {
  $dates = array();
  $current = $first;

  while( $current <= $last ) {
    $key = date($key_format, $current);
    $dates[$key] = format_date($current, 'custom', $output_format);
    $current = strtotime($step, $current);
  }

  return $dates;
}

/**
 * Implements hook_block_info()
 */
function yellow_pages_core_block_info() {

  $blocks['criteo_300_250'] = array(
    'info' => t('Criteo 300x250'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['adsense_300_250'] = array(
    'info' => t('AdSense 300x250'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['adsense_front_468_60_left'] = array(
    'info' => t('AdSense Front'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['adsense_news_728_90_first'] = array(
    'info' => t('AdSense News'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );


  $blocks['adsense_front_468_60_right'] = array(
    'info' => t('Criteo 468x60'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

/*  $blocks['adsense_news_728_90_first'] = array(
    'info' => t('AdSense News 728x90 First'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );*/

  $blocks['adsense_news_728_90_second'] = array(
    'info' => t('Criteo 728x90'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function yellow_pages_core_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();


  $block['subject'] = '';
  switch ($delta) {
    case 'adsense_front_468_60_left':
    case 'adsense_news_728_90_first':
    case 'adsense_news_728_90_second':
      $block['content'] = yellow_pages_core_get_adsense_adaptive();
      break;
    case 'adsense_300_250':
      $block['content'] = yellow_pages_core_get_adsense_300_250();
      break;
    case 'adsense_front_468_60_right':
      $block['content'] = yellow_pages_core_get_criteo_468_60();
      break;
//    case 'criteo_728_90':
 //     $block['content'] = yellow_pages_core_get_criteo_728_90();
 //     break;
    case 'criteo_300_250':
      $block['content'] = yellow_pages_core_get_criteo_300_250();
      break;

 /*   case 'adsense_company_300_250':
    case 'adsense_search_300_250':
      $block['subject'] = '';
      $block['content'] = yellow_pages_core_get_300_250_ad_block_content();
      break;

    case 'adsense_front_468_60_left':
      $block['subject'] = '';
      $block['content'] = yellow_pages_core_get_google_adsense();
      break;

    case 'adsense_front_468_60_right':
      $block['subject'] = '';
      $block['content'] = yellow_pages_core_get_468_60_ad_block_content();
      break;

    case 'adsense_news_728_90_first':
      $block['subject'] = '';
      $block['content'] = yellow_pages_core_get_google_adsense();
      break;

    case 'adsense_news_728_90_second':
      $block['subject'] = '';
      $block['content'] = yellow_pages_core_get_728_90_ad_block_content();
      break;*/


  }
  return $block;
}

/**
 * Get Criteo ad for 300x250px block.
 */
function yellow_pages_core_get_criteo_300_250() {
  return "<script type='text/javascript'>
<!--//<![CDATA[
document.MAX_ct0 ='';
var m3_u = (location.protocol=='https:'?'https://cas.criteo.com/delivery/ajs.php?':'http://cas.criteo.com/delivery/ajs.php?');
var m3_r = Math.floor(Math.random()*99999999999);
document.write (\"<scr\"+\"ipt type='text/javascript' src='\"+m3_u);
document.write (\"zoneid=384256\");document.write(\"&amp;nodis=1\");
document.write ('&amp;cb=' + m3_r);
if (document.MAX_used != ',') document.write (\"&amp;exclude=\" + document.MAX_used);
document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ?
'&amp;charset='+document.characterSet : ''));
document.write (\"&amp;loc=\" + escape(window.location).substring(0,1600));
if (document.context) document.write (\"&context=\" + escape(document.context));
if ((typeof(document.MAX_ct0) != 'undefined') && (document.MAX_ct0.substring(0,4) == 'http')) {
document.write (\"&amp;ct0=\" + escape(document.MAX_ct0));
}
if (document.mmm_fo) document.write (\"&amp;mmm_fo=1\");
document.write (\"'></scr\"+\"ipt>\");
//]]>--></script>";
}

/**
 * Get Criteo ad for 468x60px block.
 */
function yellow_pages_core_get_criteo_468_60() {
  return "<script type='text/javascript'>
<!--//<![CDATA[
document.MAX_ct0 ='';
var m3_u = (location.protocol=='https:'?'https://cas.criteo.com/delivery/ajs.php?':'http://cas.criteo.com/delivery/ajs.php?');
var m3_r = Math.floor(Math.random()*99999999999);
document.write (\"<scr\"+\"ipt type='text/javascript' src='\"+m3_u);
document.write (\"zoneid=388187\");document.write(\"&amp;nodis=1\");
document.write ('&amp;cb=' + m3_r);
if (document.MAX_used != ',') document.write (\"&amp;exclude=\" + document.MAX_used);
document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ?
'&amp;charset='+document.characterSet : ''));
document.write (\"&amp;loc=\" + escape(window.location).substring(0,1600));
if (document.context) document.write (\"&context=\" + escape(document.context));
if ((typeof(document.MAX_ct0) != 'undefined') && (document.MAX_ct0.substring(0,4) == 'http')) {
document.write (\"&amp;ct0=\" + escape(document.MAX_ct0));
}
if (document.mmm_fo) document.write (\"&amp;mmm_fo=1\");
document.write (\"'></scr\"+\"ipt>\");
//]]>--></script>";
}

/**
 * Get Criteo ad for 728x90px block.
 */
function yellow_pages_core_get_criteo_728_90() {
  return "<script type='text/javascript'>
<!--//<![CDATA[
document.MAX_ct0 ='';
var m3_u = (location.protocol=='https:'?'https://cas.criteo.com/delivery/ajs.php?':'http://cas.criteo.com/delivery/ajs.php?');
var m3_r = Math.floor(Math.random()*99999999999);
document.write (\"<scr\"+\"ipt type='text/javascript' src='\"+m3_u);
document.write (\"zoneid=388188\");document.write(\"&amp;nodis=1\");
document.write ('&amp;cb=' + m3_r);
if (document.MAX_used != ',') document.write (\"&amp;exclude=\" + document.MAX_used);
document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ?
'&amp;charset='+document.characterSet : ''));
document.write (\"&amp;loc=\" + escape(window.location).substring(0,1600));
if (document.context) document.write (\"&context=\" + escape(document.context));
if ((typeof(document.MAX_ct0) != 'undefined') && (document.MAX_ct0.substring(0,4) == 'http')) {
document.write (\"&amp;ct0=\" + escape(document.MAX_ct0));
}
if (document.mmm_fo) document.write (\"&amp;mmm_fo=1\");
document.write (\"'></scr\"+\"ipt>\");
//]]>--></script>";
}


/**
 * Get google AdSense block for 300x250
 */
function yellow_pages_core_get_adsense_300_250() {
  return "<script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"></script>
<!-- yp.md&yellowpages.md_300x250px -->
<ins class=\"adsbygoogle\"
 style=\"display:inline-block;width: 100%; height: 250px\"
 data-ad-client=\"ca-pub-4252189351312901\"
 data-ad-slot=\"1584816871\"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>";
}


/**
 * Get google AdSense adaptive block content.
 */
function yellow_pages_core_get_adsense_adaptive() {
  if (in_array($_SERVER['SERVER_NAME'], array('yp.md', 'www.yp.md'))) {
    return '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- yp.md_auto -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-4252189351312901"
       data-ad-slot="9560898878"
       data-ad-format="auto"></ins>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>';
  }
  else {
    return '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- yellowpages.md_auto -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-4252189351312901"
       data-ad-slot="2037632074"
       data-ad-format="auto"></ins>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>';
  }
}
