<?php
/**
 * @file
 * Synchronize data with MDB.
 */

 define('SYNC_VOCABULARY', 'products');
 define('SYNC_BATCH', 5);

/**
 * Implements hook_menu().
 */
function yellow_pages_sync_menu() {
  $items = array();

  $items['admin/config/yp/sync'] = array(
    'title' => 'Synchronize',
    'description' => 'Setup data sync from MDB source.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('yellow_pages_sync_admin_form'),
    'access arguments' => array('administer yellow pages sync'),
    'file' => 'yellow_pages_sync.admin.inc',
  );

  return $items;
}

function yellow_pages_sync_nodes(&$context) {
  if (!isset($context['sandbox']['progress'])) {
    $xml_file = drupal_get_path('module', 'yellow_pages_sync') . '/data/enterprises.xml';
    $xml_data = file_get_contents($xml_file);

    $xml = new SimpleXMLElement($xml_data);
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['max'] = (int) $xml->count;
  }

  $languages = array_keys(locale_language_list('name'));
  $node_defaults = array(
    'type' => 'company',
    'language' => 'ru',
    'uid' => 1,
    'status' => 0,
    'promote' => 0,
  );
  $voc = taxonomy_vocabulary_machine_name_load(SYNC_VOCABULARY);

  foreach ($xml->results->{'list-item'} as $list_item) {
    $item = yellow_page_sync_process_source_element($list_item);
    $tnid = NULL;

    $context['sandbox']['progress']++;
//     $context['message'] = t('Now processing %title', array('%title' => $source->title));

    // Basics.
    $node_defaults['language'] = 'ru';
    $entity = entity_create('node', $node_defaults);

    // Title.
    $entity->title = $item['title']['ru'];
    // Emails.
    if (!empty($item['email'])) {
      foreach ($item['email'] as $k => $email) {
        $entity->field_email[LANGUAGE_NONE][$k]['email'] = $email;
      }
    }
    // URL's.
    if (!empty($item['url'])) {
      foreach ($item['url'] as $k => $url) {
        $entity->field_company_site[LANGUAGE_NONE][$k]['url'] = $url;
      }
    }
    // Products.
    if (!empty($item['products']['ru'])) {
      foreach ($item['products']['ru'] as $k => $tid) {
        $entity->field_products[LANGUAGE_NONE][]['tid'] = $tid;
      }
    }
    // Addresses.
    if (!empty($item['addresses'])) {
      foreach ($item['addresses'] as $k => $address) {
        $entity->field_address[LANGUAGE_NONE][] = array(
          'country' => 'MD',
          'locality' => $address['city'],
          'postal_code' => $address['pcode'],
          'thoroughfare' => $address['address'],
          'premise' => $address['premise'],
        );
      }
    }
    // Sync time.
    $entity->field_mdb_sync_date[LANGUAGE_NONE][0]['value'] = date('Y-m-d H:i:s', time());

    // Save new node.
    node_save($entity);

    // Update node parent.
    $tnid = $entity->nid;
    db_update('node')
      ->fields(array('tnid' => $tnid))
      ->condition('nid', $entity->nid, '=')
      ->execute();

    // Translations.
//     foreach ($languages as $lang) {
//       if ($lang == 'ru') {
//         continue;
//       }

//       $node_defaults['language'] = $lang;
//       $translated_entity = entity_create('node', $node_defaults);

//       // Fields.
//       yellow_pages_sync_fill_entity($translated_entity, $source);

//       // Parent reference.
//       $translated_entity->tnid = $tnid;

//       node_save($translated_entity);
//     }
  }

//   if ($context['sandbox']['progress'] != $context['sandbox']['max']) {
//     $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
//   }
}

function yellow_page_sync_process_source_element(SimpleXMLElement $source) {
  $result = array();
  // Title.
  $result['title'] = yellow_pages_sync_process_source_element_title($source);
  $result['email'] = yellow_pages_sync_process_source_element_email($source);
  $result['url']   = yellow_pages_sync_process_source_element_url($source);
  $result['products'] = yellow_pages_sync_process_source_element_products($source);
  $result['addresses'] = yellow_pages_sync_process_source_element_address($source);

  return $result;
}

function yellow_pages_sync_process_source_element_title(SimpleXMLElement $source) {
  $source_title = $source->titles;
  $titles = array();
  $locales = array('ru', 'ro', 'en');

  foreach ($source_title->{'list-item'} as $item) {
    if ((string) $item->title_type == 'DE JURE') {
      foreach ($locales as $locale) {
        $titles[$locale] = (string) $item->title . ' ' . (string) $source->enterprise_type->{$locale . '_field'};
        if (!empty((string) $item->appendix->{$locale . '_field'})) {
          $titles[$locale] .= ', ' . (string) $item->appendix->{$locale . '_field'};
        }
      }
    }
    elseif ((string) $item->title_type == 'DE FACTO') {
      foreach ($locales as $locale) {
        $titles[$locale] .= ' / ' . (string) $item->title . ' ' . (string) $item->appendix->{$locale . '_field'};
      }
    }
  }


  yellow_pages_sync_trim($titles);

  return $titles;
}

function yellow_pages_sync_process_source_element_email(SimpleXMLElement $source) {
  $source_email = $source->emails;
  $emails = array();

  if (isset($source_email->{'list-item'})) {
    foreach ($source_email->{'list-item'} as $item) {
      $emails[] = (string) $item;
    }
  }

  yellow_pages_sync_trim($emails);

  return $emails;
}

function yellow_pages_sync_process_source_element_url(SimpleXMLElement $source) {
  $source_url = $source->www_set;
  $urls = array();

  if (isset($source_url->{'list-item'})) {
    foreach ($source_url->{'list-item'} as $item) {
      $urls[] = (string) $item;
    }
  }

  return $urls;
}

function yellow_pages_sync_process_source_element_products(SimpleXMLElement $source) {
  $source_products = $source->products;
  $products = array();
  $locales = array('ru', 'ro', 'en');

  if (isset($source_products->{'list-item'})) {
    foreach ($source_products->{'list-item'} as $item) {
      $p = $item->product;
      foreach ($locales as $locale) {
        $products[$locale][] = $p->{$locale . '_field'};
      }
    }
  }

  // @todo
  // Process all locales and create related terms.
  array_walk($products['ru'], function(&$product) {
    $vid = yellow_pages_sync_term_target_vocabulary();
    $product = yellow_pages_sync_create_term($product, $vid);
  });

  return $products;
}

function yellow_pages_sync_process_source_element_address(SimpleXMLElement $source) {
  $source_address = $source->locations;
  $addresses = array();

  if (isset($source_address->{'list-item'})) {
    foreach ($source_address->{'list-item'} as $item) {
      $street = (string) $item->street->EN_field;
      $house = (string) $item->house->EN_field;
      $office = (string) $item->office;

      $thoroughfare = str_replace(array('bd.', 'str.'), '', $street);
      if (!empty($house)) {
        $thoroughfare .= ', ' . $house;
      }

      $addresses[] = array(
        'city' => str_replace(array('mun.', 'or.', 's.'), '', (string) $item->town->EN_field),
        'pcode' => (int) $item->pcode->{'list-item'},
        'address' => $thoroughfare,
        'premise' => $office,
      );
    }
  }

  return $addresses;
}

function yellow_pages_sync_term_target_vocabulary() {
  $vid = &drupal_static(__FUNCTION__, NULL);

  if (!$vid) {
    $voc = taxonomy_vocabulary_machine_name_load(SYNC_VOCABULARY);
    $vid = $voc->vid;
  }

  return $vid;
}

function yellow_pages_sync_trim(array $input) {
  array_walk($input, function (&$v) {
    $v = trim($v);
  });

  return $input;
}

function yellow_pages_sync_create_term($name, $vid, $parent = NULL) {
  $name = trim($name);

  $term = taxonomy_get_term_by_name($name);
  if (empty($term)) {
    $term = new stdClass();
    $term->name = $name;
    $term->vid = $vid;

    if ($parent) {
      $term->parent = (int) $parent;
    }

    taxonomy_term_save($term);
  }
  else {
    $term = reset($term);
  }

  return $term->tid;
}

function yellow_pages_sync_batch_finish($success, $results, $operations) {
  drupal_get_messages();
  if ($success) {
    drupal_set_message(t('Synchronisation process complete.'));
  }
  else {
    drupal_set_message(t('Synchronisation process failed.'), 'error');
  }
}
