<?php
/**
 * @file
 * Collect Yellow Pages site statistics.
 */

include_once 'yellow_pages_statistics.features.inc';

/**
 * Implements hook_init().
 */
function yellow_pages_statistics_init() {
  $module_path = drupal_get_path('module', 'yellow_pages_statistics');

  // Add js file to count clicks to advertisements and companies sites links.
  drupal_add_js($module_path . '/js/yellow_pages_statistics_link_click.js');
}

/**
 * Implements hook_permission().
 */
function yellow_pages_statistics_permission() {
  return array(
    'administer yellow pages statistics' => array(
      'title' => t('Administer Yellow Pages statistics'),
    ),
    'access yellow pages node statistics' => array(
      'title' => t('Access Yellow Pages node statistics'),
    ),
    'access yellow pages search statistics' => array(
      'title' => t('Access Yellow Pages search statistics'),
    ),
    'access yellow pages google analytics page' => array(
      'title' => t('Access Yellow Pages Google Analytics page'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function yellow_pages_statistics_menu() {
  $items = array();

  $items['google-analytics'] = array(
    'title' => 'Google Analytics',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('yellow_pages_statistics_ga'),
    'access arguments' => array('access yellow pages google analytics page'),
    'file' => 'yellow_pages_statistics.ga.inc',
    'type' => MENU_CALLBACK,
  );

  $items['search-statistics'] = array(
    'title' => 'Search statistics',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('yellow_pages_search_statistics'),
    'access arguments' => array('access yellow pages search statistics'),
    'file' => 'yellow_pages_statistics.reports.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/yp/ga_client'] = array(
    'title' => 'GA data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('yellow_pages_statistics_ga_client_settings_form'),
    'access arguments' => array('administer yellow pages statistics'),
    'file' => 'yellow_pages_statistics.admin.inc',
  );

  $items['ajax/count/advertisement/%'] = array(
    'title' => 'Advertisement statistics tracker',
    'page callback' => 'yellow_pages_statistics_tracker',
    'page arguments' => array(2, 3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['ajax/count/company/%'] = array(
    'title' => 'Enterprise statistics tracker',
    'page callback' => 'yellow_pages_statistics_tracker',
    'page arguments' => array(2, 3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['ajax/ads-nvc'] = array(
    'page callback' => 'yellow_pages_statistics_nvc_count_node_view_ajax',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['node/%node/yp-statistics'] = array(
    'title' => 'Statistics',
    'page callback' => 'yellow_pages_statistics_node_stat',
    'page arguments' => array(1),
    'access arguments' => array('access yellow pages node statistics'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'yellow_pages_statistics.reports.inc',
    'weight' => 50,
  );

  $items['yp-form-action'] = array(
    'title' => 'Statistics',
    'page callback' => 'yellow_pages_statistics_node_stat',
    'page arguments' => array(1),
    'access arguments' => array('access yellow pages node statistics'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'yellow_pages_statistics.reports.inc',
    'weight' => 50,
  );

  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function yellow_pages_statistics_admin_paths() {
  $paths = array(
    'node/*/yp-statistics' => TRUE,
  );
  return $paths;
}

/**
 * Callback page function for tracking advertisement node clicks and redirect
 * to its link field value.
 *
 * @param $node
 *   Advertisement node object.
 */
function yellow_pages_statistics_tracker($type, $nid) {
  if ($type == 'advertisement') {
    // Insert statistics information.
    $fields = array(
      'nid' => $nid,
      'timestamp' => time(),
    );
    if (!empty($_SERVER['HTTP_REFERER'])) {
      $fields['http_referer'] = $_SERVER['HTTP_REFERER'];
    }

    db_insert('yp_ad_statistics')
      ->fields($fields)
      ->execute();
  }
  elseif ($type == 'company') {
    // Insert statistics information.
    $fields = array(
      'nid' => $nid,
      'timestamp' => time(),
    );

    db_insert('yp_company_statistics')
      ->fields($fields)
      ->execute();
  }
}

/**
 * Implements hook_node_delete().
 */
function yellow_pages_statistics_node_delete($node) {
  if ($node->type == 'advertisement') {
    // Remove statistics for deleted node.
    db_delete('yp_ad_statistics')
      ->condition('nid', $node->nid)
      ->execute();
    // Remove node views for deleted node.
    db_delete('yp_ad_nodeviewcount')
      ->condition('nid', $node->nid)
      ->execute();
  }
  elseif ($node->type == 'company') {
    // Remove statistics for deleted node.
    db_delete('yp_company_statistics')
      ->condition('nid', $node->nid)
      ->execute();
  }
}

/**
 * Implements hook_node_view().
 */
function yellow_pages_statistics_node_view($node, $view_mode, $langcode) {
  if (!user_is_anonymous() || $node->type != 'advertisement') {
    return FALSE;
  }

  $js_setting = array(
    'yp_ads_nvc' => array($node->nid),
  );
  drupal_add_js($js_setting, 'setting');

  $module_path = drupal_get_path('module', 'yellow_pages_statistics');
  drupal_add_js($module_path . '/js/yellow_pages_statistics.nvc.js');
}

/**
 * Page callback: Add node view ajax.
 */
function yellow_pages_statistics_nvc_count_node_view_ajax() {
  if (!empty($_POST['nids'])) {
    $nids = json_decode($_POST['nids']);
    if (!empty($nids)) {
      foreach ($nids as $nid) {
        $fields = array(
          'nid' => $nid,
          'timestamp' => REQUEST_TIME,
        );
        drupal_write_record('yp_ad_nodeviewcount', $fields);
      }
    }
  }
}

/**
 * Implements hook_views_post_execute().
 */
function yellow_pages_statistics_views_post_execute(&$view) {
  $search_company = ($view->current_display == 'solr_node_search');
  $search_news = ($view->current_display == 'panel_pane_2');
  $no_adv_view = empty($view->advertisement_call);
  $has_argument = !empty($view->args[0]);

  if (($search_company || $search_news) && $no_adv_view && $has_argument) {
    // Add keywords statistics.
    $timestamp = time();
    $keywords = $view->args[0];
    $fields = array(
      'keywords' => $keywords,
      'timestamp' => $timestamp,
    );
    drupal_write_record('yp_search_statistics', $fields);

    // Add company search statistics.
    if (!$search_news) {
      $page = !empty($view->query->pager->current_page) ? $view->query->pager->current_page : 0;
      $entities = $view->result;
      foreach($entities as $entity) {
        if (!empty($entity->_entity_properties['search_api_id'])) {
          $fields = array(
            'page' => $page,
            'keywords' => $keywords,
            'timestamp' => $timestamp,
            'nid' => $entity->entity,
          );
          drupal_write_record('yp_search_company_statistics', $fields);
        }
      }
    }
  }
}
