<?php
/**
 * @file
 * Code for the Yellow Pages Taxonomy feature.
 */

include_once 'yellow_pages_taxonomy.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function yellow_pages_taxonomy_form_taxonomy_form_term_alter(&$form, &$form_state) {
  // Hide standard 'description' field.

  // Unfold related items.
  $form['relations']['#type'] = 'container';
  $form['relations']['#collapsible'] = FALSE;
  $form['relations']['#collapsed'] = FALSE;

  // Change 'parent term' field title.
  $form['relations']['parent']['#title'] = t('Parent category');
}
