<?php
/**
 * @file
 * Code for the Yellow Pages Taxonomy feature.
 */

include_once 'yellow_pages_taxonomy.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function yellow_pages_taxonomy_form_taxonomy_form_term_alter(&$form, &$form_state) {
  // Change 'parent term' field title.
  $form['relations']['parent']['#title'] = t('Parents');
  $form['relations']['#collapsed'] = FALSE;

  // Fold the path alias fieldset.
  $form['path']['#collapsed'] = TRUE;
}
