<?php
/**
 * @file
 * Provides various content lists.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function yellow_pages_lists_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 *
 * @param stdClass $context
 */
function yellow_pages_lists_similar_articles(stdClass $context) {
  $references = yellow_pages_lists_get_references($context);
  $relations = yellow_pages_lists_get_relations($context);

  $nids = array_slice(array_merge($references, $relations), 0, 3);
  $nodes = node_load_multiple($nids);

  $content = array();
  foreach ($nodes as $node) {
    $render = node_view($node, 'teaser');
    $content[] = drupal_render($render);
  }

  return implode('', $content);
}

function yellow_pages_lists_get_relations(stdClass $context) {
  $relations = array();
  $tids = array();
  if (!empty($context->field_products)) {
    foreach ($context->field_products[LANGUAGE_NONE] as $relation) {
      $tids[] = $relation['tid'];
    }
  }

  global $language;

  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'article')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->propertyCondition('language', $language->language)
    ->fieldCondition('field_products', 'tid', $tids, 'IN')
    ->range(0, 3);
  $result = $query->execute();

  if (isset($result['node'])) {
    $relations = array_keys($result['node']);
  }

  return $relations;
}

function yellow_pages_lists_get_references(stdClass $context) {
  $references = array();

  if (!empty($context->field_articles)) {
    foreach ($context->field_articles[LANGUAGE_NONE] as $reference) {
      $references[] = $reference['target_id'];
    }
  }

  return $references;
}

function yellow_pages_lists_news_carousel() {
  $nids = yellow_pages_lists_get_latest_news();
  $nodes = node_load_multiple($nids);

  $ads_nids = yellow_pages_lists_get_news_ads();
  $ads_nodes = node_load_multiple($ads_nids);
  $content = array();

  $entropy = round(count($nodes) / count($ads_nodes));
  $i = 0;
  while (TRUE) {
    if (empty($nodes) && empty($ads_nodes)) {
      break;
    }

    if (!empty($nodes)) {
      $render = node_view(array_pop($nodes), 'slider_teaser');
      $content[] = drupal_render($render);
    }

    if (!empty($ads_nodes) && ($entropy == 0 || $i % $entropy == 0)) {
      $render = node_view(array_pop($ads_nodes), 'slider_teaser');
      $content[] = drupal_render($render);
    }

    $i++;
  }

  return implode('', $content);
}

function yellow_pages_lists_get_latest_news() {
  global $language;

  $news = array();

  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'news')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->propertyCondition('language', $language->language)
    ->propertyOrderBy('created', 'DESC')
    ->range(0, 50);
  $result = $query->execute();

  if (isset($result['node'])) {
    $news = array_keys($result['node']);
  }

  return $news;
}

function yellow_pages_lists_get_news_ads() {
  global $language;

  $ads = array();

  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'advertisement')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->propertyCondition('language', $language->language)
    ->fieldCondition('field_ad_category', 'value', 'frontpage', '=');
  $result = $query->execute();

  if (isset($result['node'])) {
    $ads = array_keys($result['node']);
  }

  shuffle($ads);

  return $ads;
}
