<?php
/**
 * @file
 * Code for the Yellow pages rules configuration feature.
 */

include_once 'yellow_pages_rules_configuration.features.inc';

/**
 * Implements hook_cron().
 */
function yellow_pages_rules_configuration_cron() {
  $tod = mktime(0, 0, 0);
  $week = 7 * 24 * 60 * 60;

  $result = db_query('SELECT n.nid FROM {node} n
      JOIN {node_expire} ne ON n.nid = ne.nid
      WHERE ne.expire = :ne_expire',
      array(':ne_expire' => $tod + $week));

  foreach ($result as $record) {
    $node = node_load($record->nid);
    rules_invoke_event('node_expire_in_week', $node);
  }
}
